---
# Common variables for system configuration
# User identification variables
real_user: alikebrahim
real_user_home: "/home/alikebrahim"

# Application and configuration directories
fonts_dir: "{{ real_user_home }}/.local/share/fonts"
apps_dir: "{{ real_user_home }}/Apps"
dotfiles_path: "{{ real_user_home }}/.dotfiles"
dotfiles_repo: "https://github.com/alikebrahim/dotfiles.git"

# Legacy variables mapping - for backward compatibility
# These will be fully removed in a future update
ansible_user_home: "{{ real_user_home }}"
ansible_user_real: "{{ real_user }}"

# Common package lists
cargo_packages:
  - ripgrep
  - fd-find
  - eza
  - zoxide
  - tokei
  - bat
  - git-delta

# Dotfiles configuration
dotfiles_packages:
  - zsh
  - nvim
  - tmux
  - wezterm
  - obsidian
  - atuin
  - git

# System packages
core_packages:
  - curl
  - git
  - stow
  - jq
  - unzip
  - wget
  - zsh
  - xclip
  - tldr

dev_packages:
  - make
  - automake
  - cmake
  - g++
  - gcc
  - build-essential
  - python3-dev
  - python3-pip
  - libevent-dev
  - ncurses-dev
  - bison
  - libfuse2
  - libssl-dev
  - ninja-build
  - gettext
  - libtool
  - libtool-bin
  - autoconf
  - pkg-config
  - yasm
  - nasm
  - meson
  - texinfo
  - git-core

tools_packages:
  - wezterm-nightly
  - neofetch
  - tree
  - 1password-cli
  - 1password
  - gh
  - transmission
  - nvme-cli
  - qemu-system
  - qemu-kvm
  - virt-manager