---
# Common variables for Pop!_OS configuration
# Define real user and home variables for consistent user identification
real_user: alikebrahim
real_user_home: "/home/alikebrahim"
# Legacy variables - to be replaced during refactoring
ansible_user_home: "{{ lookup('env', 'HOME') }}"
ansible_user_real: alikebrahim
fonts_dir: "{{ real_user_home }}/.local/share/fonts"
apps_dir: "{{ real_user_home }}/Apps"
dotfiles_path: "{{ real_user_home }}/.dotfiles"
dotfiles_repo: "https://github.com/alikebrahim/dotfiles.git"

# Common package lists
cargo_packages:
  - ripgrep
  - fd-find
  - eza
  - zoxide
  - tokei
  - bat
  - git-delta

# Dotfiles configuration
dotfiles_packages:
  - zsh
  - nvim
  - tmux
  - wezterm
  - obsidian
  - atuin
  - git

# Pop!_OS specific packages
popos_core_packages:
  - curl
  - git
  - stow
  - jq
  - unzip
  - wget
  - zsh
  - xclip
  - tldr

popos_dev_packages:
  - make
  - automake
  - cmake
  - g++
  - gcc
  - build-essential
  - python3-dev
  - python3-pip
  - libevent-dev
  - ncurses-dev
  - bison
  - libfuse2
  - libssl-dev
  - ninja-build
  - gettext
  - libtool
  - libtool-bin
  - autoconf
  - pkg-config
  - yasm
  - nasm
  - meson
  - texinfo
  - git-core

popos_tools_packages:
  - wezterm-nightly
  - neofetch
  - tree
  - 1password-cli
  - 1password
  - gh
  - transmission
  - nvme-cli
