---
# Pop!_OS specific variables
popos_core_packages:
  - curl
  - git
  - stow
  - jq
  - unzip
  - wget
  - zsh
  - htop
  - build-essential
  - ninja-build
  - gettext
  - libtool
  - libtool-bin
  - autoconf
  - automake
  - cmake
  - g++
  - pkg-config

popos_dev_packages:
  - libevent-dev
  - ncurses-dev
  - bison
  - python3-dev
  - python3-pip
  - gcc
  - make
  - libfuse2
  - libssl-dev

popos_tools_packages:
  - tldr
  - neofetch
  - tree
