- name: Add git ppa
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa

- name: Update the apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Create directory for Docker keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt sources
  ansible.builtin.copy:
    content: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    dest: /etc/apt/sources.list.d/docker.list

- name: Download and add Wezterm GPG key
  ansible.builtin.shell: curl -fsSL https://apt.fury.io/wez/gpg.key | gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg

- name: Add Wezterm repository to sources list
  ansible.builtin.copy:
    content: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *\n"
    dest: /etc/apt/sources.list.d/wezterm.list

- name: Update APT package index and update system
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
