# Obsidian
- name: Create ~/.local/bin directory
  ansible.builtin.shell:
    cmd: mkdir -p "{{ ansible_env.HOME }}/.local/bin"
  become_user: alikebrahim
  # become: true
  tags: ["obsidian","productivity"]

- name: Download Obsidian
  ansible.builtin.uri:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.5/Obsidian-1.6.5.AppImage
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: '0755'
  tags: ["obsidian","productivity"]

- name: Set obsidian AppImage permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: file
    mode: '0o755'
  become_user: alikebrahim
  become: true
  tags: ["obsidian","productivity"]
