# Obsidian
- name: Create ~/.local/bin directory
  ansible.builtin.shell:
    cmd: mkdir -p "{{ ansible_env.HOME }}/.local/bin"
  become_user: alikebrahim
  become: yes

- name: Download Obsidian
  ansible.builtin.uri:
  url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.5/Obsidian-1.6.5.AppImage
  dest: ~/.local/bin/obsidian

- name: Set obsidian AppImage permissions
  ansible.builtin.file:
    path: ~/.local/bin/obsidian
    state: file
    mode: '0o755'
  become_user: alikebrahim
  become: yes
