- name: Create JuliaMono font directory
  ansible.builtin.file:
    path: /home/alikebrahim/.local/share/fonts/JuliaMono
    state: directory
    mode: '0755'

- name: Create JetBrains font directory
  ansible.builtin.file:
    path: /home/alikebrahim/.local/share/fonts/JetBrains
    state: directory
    mode: '0755'

- name: Install JuliaMono
  ansible.builtin.unarchive:
    src: 'https://github.com/cormullion/juliamono/releases/download/v0.056/JuliaMono-ttf.tar.gz'
    dest: "/home/alikebrahim/.local/share/fonts/JuliaMono"
    remote_src: true

- name: Install JetBrains
  ansible.builtin.unarchive:
    src: 'https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip'
    dest: "/home/alikebrahim/.local/share/fonts/JetBrains"
    remote_src: true

- name: Config Stow
  ansible.builtin.command:
    cmd: stow -t ~ -d '/home/alikebrahim/.dotfiles/' zsh nvim fzf tmux wezterm obsidian atuin
    # chdir: "/home/alikebrahim/.dotfiles"

- name: Set zsh shell
  ansible.builtin.shell:
    cmd: chsh -s $(which zsh) alikebrahim
  become: true

# - name: Checking if oh-my-zsh exists
#   stat:
#     path: "/home/alikebrahim/.oh-my-zsh"
#   register: oh_my_stats

# - name: Oh-My-Zsh
#   ansible.builtin.shell:
#     cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
#   when: oh_my_stats.stat.exists == False
#   become_user: alikebrahim

# - name: Install zsh-syntax-highlightinh
#   ansible.builtin.git:
#     repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
#     dest: "/home/alikebrahim/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
#     clone: true
#     update: true
#     force: true
#   become_user: alikebrahim

# - name: Install zsh-autosuggestions
#   ansible.builtin.git:
#     repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
#     dest: "/home/alikebrahim/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
#     clone: true
#     update: true
#     force: true
#   become_user: alikebrahim

- name: Set wezterm as default terminal
  ansible.builtin.command:
    cmd: update-alternatives --set x-terminal-emulator /usr/bin/open-wezterm-here
  become: true
  become_method: sudo
  # become_user: alikebrahim

- name: Update tldr database
  ansible.builtin.command:
    cmd: tldr -u
  become_user: alikebrahim

- name: Update font cache
  ansible.builtin.command:
    cmd: fc-cache -r
  become_user: alikebrahim
