# go
- name: Get go latest version
  ansible.builtin.shell:
    cmd: curl -Ls "https://golang.org/dl/?mode=json" | jq -r '.[0].version'
  register: go_version

- name: Download go tarball
  ansible.builtin.get_url:
    url: https://go.dev/dl/{{ go_version.stdout }}.linux-amd64.tar.gz
    dest: /tmp/{{ go_version.stdout }}.linux-amd64.tar.gz

- name: Install go
  ansible.builtin.shell:
    cmd: rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/{{ go_version.stdout }}.linux-amd64.tar.gz
  become: true

- name: Create go directories
  ansible.builtin.file:
    path: /home/alikebrahim/go/{{ item }}
    state: directory
    owner: alikebrahim
    group: alikebrahim
    mode: '0755'
  loop:
    - src
    - pkg
    - bin
  become: true

# rust
- name: Download rust installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: '0755'

- name: Install rust
  ansible.builtin.shell: sh /tmp/rustup.sh -y
  args:
    creates: /home/alikebrahim/.cargo/bin/rustc
  become_user: alikebrahim

- name: Source cargo env to activate it
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.cargo/env
  args:
    executable: /bin/bash
  become_user: alikebrahim
  # become: yes
  when: ansible_env.HOME is defined

# - name: Activate cargo env
#   ansible.builtin.shell: . $HOME/.cargo/env
#   become_user: alikebrahim

# - name: Set default rust toolchain to stable
#   ansible.builtin.shell: /home/alikebrahim/.cargo/bin/rustup default stable
#   become_user: alikebrahim

# nvm & node
- name: Install Node Version Manager (NVM)
  ansible.builtin.shell:
    cmd: bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  environment:
    PROFILE: /dev/null
  become_user: alikebrahim
  # become: yes

- name: Source NVM script to activate it
  ansible.builtin.shell:
    cmd: . "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  args:
    executable: /bin/bash
  become_user: alikebrahim
  # become: yes
  when: ansible_env.HOME is defined

# pyenv
- name: Install pyenv
  ansible.builtin.shell:
    cmd: curl https://pyenv.run | bash
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv"
  environment:
    PROFILE: /dev/null
  become_user: alikebrahim


# zig
# java
