# go
- name: Get go latest version
  ansible.builtin.shell:
    cmd: curl -Ls "https://golang.org/dl/?mode=json" | jq -r '.[0].version'
  register: go_version
  tags: ["go", "languages"]

- name: Install go
  ansible.builtin.unarchive:
    src: https://go.dev/dl/{{ go_version.stdout }}.linux-amd64.tar.gz
    dest: "/usr/local"
    creates: "/usr/local/go/"
    remote_src: true
  become: true
  tags: ["go", "languages"]

- name: Create go directories
  ansible.builtin.file:
    path: /home/alikebrahim/go/{{ item }}
    state: directory
    owner: alikebrahim
    group: alikebrahim
    mode: '0755'
  loop:
    - src
    - pkg
    - bin
  become: true
  tags: ["go", "languages"]

# rust
- name: Download rust installer
  ansible.builtin.get_url:
    url: "https://sh.rustup.rs"
    dest: "/tmp/rustup.sh"
    mode: '0755'
  tags: ["rust", "languages"]

- name: Install rust
  ansible.builtin.shell: sh /tmp/rustup.sh -y
  args:
    creates: "/home/alikebrahim/.cargo/bin/rustc"
  become_user: alikebrahim
  tags: ["rust", "languages"]

- name: Source cargo env to activate it
  ansible.builtin.shell:
    cmd: ". /home/alikebrahim/.cargo/env"
  args:
    executable: "/bin/bash"
  become_user: alikebrahim
  tags: ["rust", "languages"]

# nvm & node
- name: Install Node Version Manager (NVM)
  ansible.builtin.shell:
    cmd: bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
  args:
    creates: "/home/alikebrahim/.nvm/nvm.sh"
  environment:
    PROFILE: "/dev/null"
  become_user: alikebrahim
  tags: ["nvm", "node", "languages"]

- name: Source NVM and Install node
  ansible.builtin.shell:
    cmd: |
      source /home/alikebrahim/.nvm/nvm.sh
      nvm install node
  environment:
    PROFILE: "/dev/null"
  args:
    executable: /bin/bash
  become: true
  become_user: alikebrahim
  tags: ["nvm", "node", "languages"]

# pyenv
- name: Install pyenv
  ansible.builtin.shell:
    cmd: curl https://pyenv.run | bash
  args:
    creates: "/home/alikebrahim/.pyenv"
  environment:
    PROFILE: /dev/null
  become_user: alikebrahim
  tags: ["pyenv", "languages"]

# zig
# java
