---
# System packages role main tasks

# System packages role tasks
- name: Running system packages role
  ansible.builtin.debug:
    msg: "Running system packages role"
  tags: [always, system]

- name: Include repository configuration
  ansible.builtin.include_tasks: repositories.yml
  tags: [repositories, apt_repositories, system]

- name: Include package installation
  ansible.builtin.include_tasks: packages.yml
  tags: [packages, system]