---
# System apt repositories configuration

# System apt keyrings
- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
  become: true
  tags: [apt_repositories, repositories]

# Docker repository setup
- name: Add Docker GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    creates: /etc/apt/keyrings/docker.asc
  become: true
  tags: [apt_repositories, repositories]


- name: Add Docker repository
  ansible.builtin.shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    creates: /etc/apt/sources.list.d/docker.list
  become: true
  tags: [apt_repositories, repositories]

# WezTerm repository setup
- name: Add Wezterm GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://apt.fury.io/wez/gpg.key | gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
    creates: /etc/apt/keyrings/wezterm-fury.gpg
  become: true
  tags: [apt_repositories, repositories]

- name: Add Wezterm repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
    filename: wezterm
    state: present
  become: true
  tags: [apt_repositories, repositories]

# GitHub CLI repository setup
- name: Download GitHub CLI GPG key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
  become: true
  tags: [apt_repositories, repositories]

- name: Add GitHub CLI repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    filename: github-cli
    state: present
  become: true
  tags: [apt_repositories, repositories]

# 1Password repository setup
- name: Add 1Password GPG key for apt repository
  ansible.builtin.shell:
    cmd: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
    creates: /usr/share/keyrings/1password-archive-keyring.gpg
  become: true
  tags: [apt_repositories, repositories]

- name: Add 1Password APT repository
  ansible.builtin.shell:
    cmd: echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | tee /etc/apt/sources.list.d/1password.list
    creates: /etc/apt/sources.list.d/1password.list
  become: true
  tags: [apt_repositories, repositories]

- name: Ensure debsig policies directory exists
  ansible.builtin.file:
    path: /etc/debsig/policies/AC2D62742012EA22
    state: directory
  become: true
  tags: [apt_repositories, repositories]

- name: Add 1Password debsig policy
  ansible.builtin.shell:
    cmd: curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
    creates: /etc/debsig/policies/AC2D62742012EA22/1password.pol
  become: true
  tags: [apt_repositories, repositories]

- name: Ensure debsig keyrings directory exists
  ansible.builtin.file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22
    state: directory
  become: true
  tags: [apt_repositories, repositories]

- name: Add 1Password debsig keyring
  ansible.builtin.shell:
    cmd: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
  become: true
  tags: [apt_repositories, repositories]

# Git Core PPA
- name: Add Git Core PPA repository
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present
  become: true
  tags: [apt_repositories, repositories]

# Final update cache
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: [apt_repositories, repositories]