---
galaxy_info:
  description: "Development tools configuration"
  author: "alikebrahim"
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
  
  galaxy_tags:
    - development
    - tools
    - languages
    - programming

