---
- name: Configure System Environment
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - group_vars/all.yml
  pre_tasks:
    - name: Stop PackageKit service
      ansible.builtin.systemd_service:
        name: packagekit.service
        masked: true
        state: stopped
      become: true
      ignore_errors: true
      tags: [always, system]
      
    - name: Install required Ansible collections
      ansible.builtin.command: ansible-galaxy collection install community.general
      register: collection_install
      changed_when: "'Installing' in collection_install.stdout"
      failed_when: collection_install.rc != 0
      tags: [always, system]
  
  roles:
    - pop_os
    - common
    - { role: development, tags: ['system', 'development'] }
  
  post_tasks:
    - name: Start PackageKit service
      ansible.builtin.service:
        name: packagekit.service
        masked: false
        state: started
      become: true
      ignore_errors: true
      tags: [always, system]

- name: Configure User Environment
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - group_vars/all.yml
  
  roles:
    - { role: development, tags: ['user', 'development'] }
    - dotfiles
    - apps
    - shell
    - terminal
    - fonts