---
- name: Configure Personal Workstation
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - group_vars/all.yml
    # - vault/secrets.yml
  pre_tasks:
    - name: Stop PackageKit service
      ansible.builtin.systemd_service:
        name: packagekit.service
        masked: true
        state: stopped
      become: true
      ignore_errors: true
      tags: [always]
      
    - name: Install required Ansible collections
      ansible.builtin.command: ansible-galaxy collection install community.general
      register: collection_install
      changed_when: "'Installing' in collection_install.stdout"
      failed_when: collection_install.rc != 0
      tags: [always]
    
  
  roles:
    - pop_os
    - common
    - development
    - dotfiles
    - apps
    - shell
    - terminal
    - fonts
  
  tasks:
    # All language, repository, and build tasks are now handled in the development role
  
  post_tasks:
    - name: Start PackageKit service
      ansible.builtin.service:
        name: packagekit.service
        masked: false
        state: started
      become: true
      ignore_errors: true
      tags: [always]
