- name: System Up
  hosts: localhost
  vars:
      source_key: "./.ssh/id_ed25519"
      dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  vars_files:
      - vault.yml
  become: true
  tasks:
      - name: Configure Ansible User
        ansible.builtin.include_tasks: system/debian/user.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: Configure ssh keys
        ansible.builtin.include_tasks: system/debian/ssh.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: "APT: Core Packages"
        ansible.builtin.include_tasks: system/debian/apt-core.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: "APT: Repositories"
        ansible.builtin.include_tasks: system/debian/apt-repositories.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: "APT: Build System Packages"
        ansible.builtin.include_tasks: system/debian/apt-buildSys.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: "APT: Application Packages"
        ansible.builtin.include_tasks: system/debian/apt-apps.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: Install Binaries and AppImages
        ansible.builtin.include_tasks: system/debian/binaries.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: Install Programming Languages
        ansible.builtin.include_tasks: system/debian/languages.ansible.yml
        tags: ["go", "rust", "node", "nvim", "languages"]
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: Install Cargo Packages
        ansible.builtin.include_tasks: system/debian/cargo.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: Install Go Packages
        ansible.builtin.include_tasks: system/debian/go.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: Clone Repositories
        ansible.builtin.include_tasks: system/debian/repositories.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: Build Applications
        ansible.builtin.include_tasks: system/debian/build.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"

      - name: System Configration
        ansible.builtin.include_tasks: system/debian/configuration.ansible.yml
        # when: ansible_facts['distribution'] == "Pop!_OS"
