---
- name: Configure Personal Workstation
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - group_vars/all.yml
    - "group_vars/{{ ansible_distribution | lower | replace('!', '') }}.yml"
    - vault/secrets.yml
  pre_tasks:
    - name: Stop PackageKit service
      ansible.builtin.service:
        name: packagekitd
        state: stopped
      become: true
      ignore_errors: true
      tags: [always]
      
    - name: Install required Ansible collections
      ansible.builtin.command: ansible-galaxy collection install community.general
      register: collection_install
      changed_when: "'Installing' in collection_install.stdout"
      failed_when: collection_install.rc != 0
      tags: [always]
  
  roles:
    - common
    - development
    - dotfiles
    - apps
    - shell
    - terminal
    - fonts
  
  tasks:
    - name: Include distro-specific package management
      ansible.builtin.include_tasks: "tasks/{{ ansible_distribution | lower | replace('!', '') }}/apt.yml"
      when: ansible_os_family == "Debian"
      tags: [packages]
    
    - name: Include distro-specific repositories
      ansible.builtin.include_tasks: "tasks/{{ ansible_distribution | lower | replace('!', '') }}/repositories.yml"
      when: ansible_os_family == "Debian"
      tags: [repositories]
    
    # All language, repository, and build tasks are now handled in the development role
  
  post_tasks:
    - name: Start PackageKit service
      ansible.builtin.service:
        name: packagekitd
        state: started
      become: true
      ignore_errors: true
      tags: [always]
