---
# Pop!_OS-specific package management

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: [packages, system, pop_os]

- name: Install core packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ popos_core_packages }}"
  become: true
  tags: [packages, core, system, pop_os]

- name: Install development packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ popos_dev_packages }}"
  become: true
  tags: [packages, development, system, pop_os]

- name: Install tool packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ popos_tools_packages }}"
  become: true
  tags: [packages, tools, system, pop_os]