# Goal is to build these packages (see repos.yml for repo clone)
# each package should define any env vars if neccessary (e.g. Neovim)
# and have a cron job that will pull the repo and rebuild every here and then?
# ensure running clearning commands where available
# Neovim
- name: Compile Neovim
  ansible.builtin.shell:
    cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo 
    chdir: /home/alikebrahim/src_repos/neovim
  become_user: alikebrahim
- name: Install Neovim
  ansible.builtin.shell:
    cmd: make install
    chdir: /home/alikebrahim/src_repos/neovim
  sudo: true
# Btop
# fzf
