# Goal is to build these packages (see repos.yml for repo clone)
# each package should define any env vars if neccessary (e.g. Neovim)
# and have a cron job that will pull the repo and rebuild every here and then?
# ensure running clearning commands where available
# Neovim
# Btop
# eza
# fzf
# fd
# ripgrep
# bat
# lazygit (can be installed with go: go install github.com/jesseduffield/lazygit@latest)
# wezterm
