# Goal is to build these packages (see repos.yml for repo clone)
# each package should define any env vars if neccessary (e.g. Neovim)
# and have a cron job that will pull the repo and rebuild every here and then?
# ensure running clearning commands where available
# Neovim
- name: Build Neovim
  ansible.builtin.shell:
    cmd: make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/usr/local/bin -DCMAKE_BUILD_TYPE=RelWithDebInfo"
    chdir: /home/alikebrahim/src_repos/Neovim
# Btop
# fzf
