# go
- name: Get Go Latest Version
  ansible.builtin.shell: 
    cmd: curl -Ls "https://golang.org/dl/?mode=json" | jq -r '.[0].version'
  register: go_version
- name: Download Go Tarball
  ansible.builtin.get_url:
    url: https://go.dev/dl/{{ go_version.stdout  }}.linux-amd64.tar.gz
    dest: /tmp/go{ { go_version.stdout }}.tar.gz
- name: Install Go
  ansible.builtin.shell: rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go{ { go_version.stdout }}.linux-amd64.tar.gz
  become: true
# rust
- name: Download Rust Installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: '0755'
- name: Install Rust
  ansible.builtin.shell: sh /tmp/rustup.sh -y
  args:
    creates: /home/alikebrahim/.cargo/bin/rustc
  become_user: alikebrahim

# node
# java
