# go
# rust
- name: Download Rust Installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: '0755'
- name: Install Rust
  ansible.builtin.shell: sh /tmp/rustup.sh -y
  args:
    creates: /home/alikebrahim/.cargo/bin/rustc
  become_user: alikebrahim
  register: rust_output
- name: Rutst Install Output
  ansible.builtin.debug:
    var: rust_output

# node
# java
