---
# Dotfiles management with stow

- name: Ensure stow is installed
  ansible.builtin.package:
    name: stow
    state: present
  # Note: This task will be skipped in user play since become is false
  # It's kept here for completeness, but packages should be installed in system play
  tags: [packages, dotfiles, user]

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_path }}"
    update: true
  become: false
  tags: [dotfiles, user]

- name: Fix permissions for dotfiles repository
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: directory
    mode: '0755'
    recurse: true
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  with_items:
    - { dest: "{{ real_user_home }}/.dotfiles" }
  become: false
  tags: [dotfiles, user]

- name: Apply dotfiles with stow
  ansible.builtin.command:
    cmd: stow -v {{ item }}
    chdir: "{{ dotfiles_path }}"
  loop: "{{ dotfiles_packages }}"
  register: stow_result
  changed_when: stow_result.rc == 0
  become: false
  environment:
    HOME: "{{ real_user_home }}"
  tags: [dotfiles, user]