---
# GitHub configuration tasks (user-level)

- name: Check if GitHub CLI is installed
  ansible.builtin.command: gh --version
  register: gh_version
  ignore_errors: true
  changed_when: false
  become: false
  tags: [github, development, user]
