---
# Commented out personal repositories cloning per request
# - name: Clone personal repositories
#   ansible.builtin.git:
#     repo: "{{ item.repo }}"
#     dest: "{{ item.dest }}"
#     clone: true
#     update: true
#     force: true
#   become: false
#   with_items:
#     - { repo: "git@github.com:alikebrahim/obsidian-silo.git", dest: "{{ real_user_home }}/Documents/obsidian" }
#     - { repo: "git@github.com:alikebrahim/books.git", dest: "{{ real_user_home }}/Documents/books" }
#   tags: [git_repositories, repositories, personal, user]