---
# Development tools setup

# Include system-level tasks
- name: Include system-level tasks
  ansible.builtin.include_tasks: system/main.yml
  tags: [system, development]

# Include user-level tasks
- name: Include user-level tasks
  ansible.builtin.include_tasks: user/main.yml
  tags: [user, development]