# - name: Add git ppa
#   ansible.builtin.apt_repository:
#     repo: ppa:git-core/ppa

- name: Create directory for Docker keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0o755'

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0o644'

# - name: Add Docker repository to apt sources
#   ansible.builtin.copy:
#     content: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian jammy stable
#     dest: /etc/apt/sources.list.d/docker.list
# echo \
#   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
#   $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Get OS codename
  ansible.builtin.shell: |
    . /etc/os-release && echo $VERSION_CODENAME
  register: os_codename

- name: Add Docker repository to apt sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ os_codename.stdout }} stable"
    create: yes


- name: Download and add Wezterm GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://apt.fury.io/wez/gpg.key | gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
    creates: /usr/share/keyrings/wezterm-fury.gpg

- name: Add Wezterm repository to sources list
  ansible.builtin.copy:
    content: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *\n"
    dest: /etc/apt/sources.list.d/wezterm.list

- name: Update APT package index and update system
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
