# Obsidian
- name: Create ~/.local/bin directory
  ansible.builtin.shell:
    cmd: mkdir -p "/home/alikebrahim/.local/bin"
    creates: "/home/alikebrahim/.local/bin"
  become_user: alikebrahim
  tags: ["obsidian", "productivity"]

- name: Download Obsidian
  ansible.builtin.uri:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.5/Obsidian-1.6.5.AppImage"
    dest: "/home/alikebrahim/.local/bin/obsidian"
    mode: '0o755'
    creates: "/home/alikebrahim/.local/bin/obsidian"
  tags: ["obsidian", "productivity"]

- name: Set obsidian AppImage permissions
  ansible.builtin.file:
    path: "/home/alikebrahim/.local/bin/obsidian"
    state: file
    mode: '0o755'
  become_user: alikebrahim
  become: true
  tags: ["obsidian", "productivity"]


# - name: Download chrome
#   ansible.builtin.uri:
#     url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
#     dest: "/home/alikebrahim/chrome"
#     mode: '0o755'
#     creates: "/home/alikebrahim/chrome"
#   tags: ["obsidian", "productivity"]

- name: Download chrome
  ansible.builtin.get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest: "/home/alikebrahim/"
  register: chrome_download
  become_user: alikebrahim

- name: Install chrome
  ansible.builtin.shell:
    cmd: apt install -y "{{ chrome_download.dest }}"
  become: true
