- name: Ensure .ssh directory exists.
  ansible.builtin.file:
    dest: "{{ dest_key | dirname }}"
    mode: '0o775'
    state: directory
    owner: alikebrahim
    group: alikebrahim

- name: Install ssh key
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: preserve
    owner: alikebrahim
    group: alikebrahim

- name: Install ssh key public
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: preserve
    owner: alikebrahim
    group: alikebrahim

- name: Add github to nown_hosts file
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -H github.com') }}"
    path: /home/alikebrahim/.ssh/known_hosts
    state: present

- name: Add ssh key to agent
  ansible.builtin.shell:
    cmd: eval "$(ssh-agent -s)"
  register: ssh_agent
