---
# Binary application installations

# User-level tasks
- name: Ensure binary directory exists
  ansible.builtin.file:
    path: "{{ real_user_home }}/.local/bin"
    state: directory
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  become: false
  tags: [apps, binaries, user]

- name: Ensure man directory exists
  ansible.builtin.file:
    path: "{{ real_user_home }}/.local/share/man/man1"
    state: directory
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  become: false
  tags: [apps, binaries, user]

# This file is for non-AppImage binaries that should be downloaded
# AppImages should be placed in the apps_dir and handled in main.yml

# FFmpeg - Media processing tool (User-level)
- name: Check if FFmpeg is installed
  ansible.builtin.stat:
    path: "{{ real_user_home }}/.local/bin/ffmpeg"
  register: ffmpeg_binary
  become: false
  tags: [apps, binaries, media, user]

- name: Create temporary directory for FFmpeg
  ansible.builtin.file:
    path: "/tmp/ffmpeg_install"
    state: directory
  when: not ffmpeg_binary.stat.exists
  become: false
  tags: [apps, binaries, media, user]

- name: Download FFmpeg
  ansible.builtin.get_url:
    url: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
    dest: "/tmp/ffmpeg_install/ffmpeg.tar.xz"
  when: not ffmpeg_binary.stat.exists
  become: false
  tags: [apps, binaries, media, user]

- name: Extract FFmpeg
  ansible.builtin.unarchive:
    src: "/tmp/ffmpeg_install/ffmpeg.tar.xz"
    dest: "/tmp/ffmpeg_install"
    remote_src: true
  when: not ffmpeg_binary.stat.exists
  become: false
  tags: [apps, binaries, media, user]

- name: Copy FFmpeg binaries to ~/.local/bin
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  loop:
    - { src: "/tmp/ffmpeg_install/ffmpeg-master-latest-linux64-gpl/bin/ffmpeg", dest: "{{ real_user_home }}/.local/bin/ffmpeg" }
    - { src: "/tmp/ffmpeg_install/ffmpeg-master-latest-linux64-gpl/bin/ffplay", dest: "{{ real_user_home }}/.local/bin/ffplay" }
    - { src: "/tmp/ffmpeg_install/ffmpeg-master-latest-linux64-gpl/bin/ffprobe", dest: "{{ real_user_home }}/.local/bin/ffprobe" }
  when: not ffmpeg_binary.stat.exists
  become: false
  tags: [apps, binaries, media, user]

- name: Copy FFmpeg man pages to ~/.local/share/man/man1
  ansible.builtin.copy:
    src: "/tmp/ffmpeg_install/ffmpeg-master-latest-linux64-gpl/man/man1/"
    dest: "{{ real_user_home }}/.local/share/man/man1/"
    remote_src: true
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  when: not ffmpeg_binary.stat.exists
  become: false
  tags: [apps, binaries, media, user]

- name: Clean up FFmpeg temporary directory
  ansible.builtin.file:
    path: "/tmp/ffmpeg_install"
    state: absent
  when: not ffmpeg_binary.stat.exists
  become: false
  tags: [apps, binaries, media, user]

# yt-dlp - YouTube downloader (User-level)
- name: Install yt-dlp with pip
  ansible.builtin.pip:
    name: "yt-dlp[default]"
    state: latest
    extra_args: --user
  become: false
  environment:
    HOME: "{{ real_user_home }}"
  tags: [apps, binaries, media, user]

# System-level tasks
# Ollama - Local AI model runner (System-level)
- name: Check if Ollama is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/ollama"
  register: ollama_binary
  tags: [apps, binaries, ai, system]

- name: Install Ollama
  ansible.builtin.shell:
    cmd: curl -fsSL https://ollama.com/install.sh | sh
  become: true
  when: not ollama_binary.stat.exists
  register: ollama_install
  changed_when: ollama_install.rc == 0 and not ollama_binary.stat.exists
  tags: [apps, binaries, ai, system]
