---
# Browser installations

# Google Chrome
- name: Download Google Chrome deb package
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    mode: '0644'
  register: chrome_download
  tags: [apps, browsers]

- name: Install Google Chrome
  ansible.builtin.apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present
  become: true
  tags: [apps, browsers]

- name: Clean up Chrome deb file
  ansible.builtin.file:
    path: /tmp/google-chrome-stable_current_amd64.deb
    state: absent
  when: chrome_download.changed
  tags: [apps, browsers]