---
# AppImages and binary apps

- name: Create Apps directory
  ansible.builtin.file:
    path: "{{ apps_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  become: false
  tags: [apps, user]

# Include binary installation tasks
- name: Include binary installation tasks
  ansible.builtin.include_tasks: binaries.yml
  tags: [apps, binaries]

# Include browser installation tasks  
- name: Include browser installation tasks
  ansible.builtin.include_tasks: browsers.yml
  tags: [apps, browsers]

# AppImages (User-level)
# Obsidian
- name: Download Obsidian AppImage
  ansible.builtin.get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.8.9/Obsidian-1.8.9.AppImage
    dest: "{{ apps_dir }}/obsidian"
    mode: '0755'
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  register: obsidian_download
  become: false
  tags: [ui, apps, user]

# Logseq
- name: Download Logseq AppImage
  ansible.builtin.get_url:
    url: https://github.com/logseq/logseq/releases/download/0.10.9/Logseq-linux-x64-0.10.9.AppImage
    dest: "{{ apps_dir }}/logseq"
    mode: '0755'
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  register: logseq_download
  become: false
  tags: [ui, apps, user]