---
# Common tasks across all distributions

# Only run these tasks in system play as they all require root privileges
- name: Verify this is the system play
  ansible.builtin.debug:
    msg: "Running common role in system context"
  when: ansible_play_name == 'Configure System Environment'
  tags: [always, common, system]

# Tailscale installation
- name: Check if Tailscale is installed 
  ansible.builtin.stat:
    path: /usr/bin/tailscale
  register: tailscale_binary
  become: true
  tags: [system, common, security]

- name: Install Tailscale
  ansible.builtin.shell:
    cmd: curl -fsSL https://tailscale.com/install.sh | sh
  when: not tailscale_binary.stat.exists
  register: tailscale_install
  changed_when: tailscale_install.rc == 0 and not tailscale_binary.stat.exists
  become: true
  tags: [system, common, security]

- name: Configure sudoers with template
  ansible.builtin.template:
    src: sudoers_ansible.j2
    dest: /etc/sudoers.d/ansible
    mode: '0440'
    validate: 'visudo -cf %s'
  become: true
  tags: [system, common, security]
