---
# Common tasks across all distributions

# Include SSH setup tasks
- name: Include SSH setup
  ansible.builtin.include_tasks: ssh.yml
  tags: [ssh, security]

# Tailscale installation
- name: Check if Tailscale is installed 
  ansible.builtin.stat:
    path: /usr/bin/tailscale
  register: tailscale_binary
  tags: [system]

- name: Install Tailscale
  ansible.builtin.shell:
    cmd: curl -fsSL https://tailscale.com/install.sh | sh
  when: not tailscale_binary.stat.exists
  register: tailscale_install
  changed_when: tailscale_install.rc == 0 and not tailscale_binary.stat.exists
  tags: [system]



- name: Configure sudoers with template
  ansible.builtin.template:
    src: sudoers_ansible.j2
    dest: /etc/sudoers.d/ansible
    mode: '0440'
    validate: 'visudo -cf %s'
  tags: [security]
