---
# Common tasks across all distributions

# Common tasks across all distributions
- name: Running common role
  ansible.builtin.debug:
    msg: "Running common role"
  tags: [always, common, system]

# Tailscale installation
- name: Check if Tailscale is installed 
  ansible.builtin.stat:
    path: /usr/bin/tailscale
  register: tailscale_binary
  become: true
  tags: [system, common, security]

- name: Install Tailscale
  ansible.builtin.shell:
    cmd: curl -fsSL https://tailscale.com/install.sh | sh
  when: not tailscale_binary.stat.exists
  register: tailscale_install
  changed_when: tailscale_install.rc == 0 and not tailscale_binary.stat.exists
  become: true
  tags: [system, common, security]

- name: Configure sudoers with template
  ansible.builtin.template:
    src: sudoers_ansible.j2
    dest: /etc/sudoers.d/ansible
    mode: '0440'
    validate: 'visudo -cf %s'
  become: true
  tags: [system, common, security]
