---
# SSH setup and configuration
# This is designed to be called from user play (become: false)

- name: Ensure .ssh directory exists with correct ownership
  ansible.builtin.file:
    path: "{{ real_user_home }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  become: false
  tags: [ssh, security, user]

- name: Install SSH private key
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/ssh/id_ed25519"
    dest: "{{ real_user_home }}/.ssh/id_ed25519"
    mode: '0600'
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  become: false
  tags: [ssh, security, user]

- name: Install SSH public key
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/ssh/id_ed25519.pub"
    dest: "{{ real_user_home }}/.ssh/id_ed25519.pub"
    mode: '0644'
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
  become: false
  tags: [ssh, security, user]

- name: Add GitHub to known_hosts file
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -H github.com') }}"
    path: "{{ real_user_home }}/.ssh/known_hosts"
    state: present
  become: false
  tags: [ssh, security, user]

- name: Start ssh-agent and add SSH key
  ansible.builtin.shell: |
    eval "$(ssh-agent -s)"
    ssh-add {{ real_user_home }}/.ssh/id_ed25519
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ real_user_home }}"
  become: false
  tags: [ssh, security, user]
